/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Models;

import javax.persistence.*;
import java.util.Set;
import javax.management.relation.Role;
import javax.validation.constraints.NotNull;

/**
 *
 * @author SDIRI
 */
@Entity
@Table(name = "users")
public class User {

  // An autogenerated id (unique for each user in the db)
   @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user's address
  @NotNull
  private String address;
  
  // The user's name
  @NotNull
  private String name;
  
  // The user's name
  @NotNull
  private String surname;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public User() { }

  public User(long id) { 
    this.id = id;
  }
  
  public User(String address, String name, String surname) {
    this.address = address;
    this.name = name;
    this.surname = surname;
  }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getAddress() {
    return address;
  }
  
  public void setAddress(String value) {
    this.address = value;
  }
  
  public String getName() {
    return name;
  }

  public void setName(String value) {
    this.name = value;
  }
  
  public String getSurname() {
    return name;
  }

  public void setSurname(String value) {
    this.name = value;
  }

}
